import cors from "cors";
import express, { type ErrorRequestHandler } from "express";
import rateLimit from "express-rate-limit";
import helmet from "helmet";
import { pinoHttp } from "pino-http";
import { config } from "./config.js";
import { HttpError } from "./http.js";
import { adminRouter } from "./routes/admin.js";
import { publicRouter } from "./routes/public.js";
export const app = express();
app.disable("x-powered-by");
app.set("trust proxy", "loopback");
app.use(pinoHttp());
app.use(helmet({ contentSecurityPolicy: config.NODE_ENV === "production" ? undefined : false }));
app.use(cors({ origin: config.WEB_ORIGIN, credentials: true }));
app.use(rateLimit({ windowMs: 60_000, limit: 120, standardHeaders: "draft-7", legacyHeaders: false }));
app.use(express.json({ limit: "1mb" }));
app.get("/robots.txt", (_req, res) => res.type("text/plain").send(`User-agent: *\nAllow: /\nSitemap: ${config.SITE_URL}/sitemap.xml\n`));
app.get("/sitemap.xml", (_req, res) => res.redirect(307, "/api/sitemap.xml"));
app.use("/api", publicRouter);
app.use("/api/admin", adminRouter);
app.get("/source/Income_Tax_Act_2025_as_amended_by_FA_Act_2026.pdf", (_req, res) => res.sendFile("Income_Tax_Act_2025_as_amended_by_FA_Act_2026.pdf", { root: process.cwd(), dotfiles: "deny" }));
app.use("/api", (_req, res) => res.status(404).json({ error: { code: "NOT_FOUND", message: "API route not found." } }));
const errors: ErrorRequestHandler = (error, req, res, _next) => { req.log.error(error); if (error instanceof HttpError) return res.status(error.status).json({ error: { code: "REQUEST_FAILED", message: error.message, details: error.details } }); if (error instanceof Error && error.name === "MulterError") return res.status(400).json({ error: { code: "UPLOAD_FAILED", message: error.message } }); return res.status(500).json({ error: { code: "INTERNAL_ERROR", message: "An unexpected error occurred." } }); };
app.use(errors);
