import { boolean, date, index, integer, jsonb, numeric, pgEnum, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

export const contentStatus = pgEnum("content_status", ["draft", "needs_review", "approved", "published", "rejected", "archived"]);
export const ingestionStatus = pgEnum("ingestion_status", ["discovered", "fetched", "downloaded", "parsed", "ai_processed", "needs_review", "approved", "published", "rejected", "failed"]);
export const contentType = pgEnum("content_type", ["act", "section", "rule", "notification", "circular", "order", "instruction", "amendment", "form", "case", "article", "faq", "announcement", "update"]);
export const documentType = pgEnum("document_type", ["bare_act", "rules", "notification", "circular", "judgment", "order", "instruction", "form", "other"]);

const timestamps = { createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() };

export const users = pgTable("users", { id: uuid("id").defaultRandom().primaryKey(), email: text("email").notNull(), displayName: text("display_name"), passwordHash: text("password_hash"), isActive: boolean("is_active").default(true).notNull(), ...timestamps }, (t) => [uniqueIndex("users_email_uq").on(t.email)]);
export const adminUsers = pgTable("admin_users", { userId: uuid("user_id").primaryKey().references(() => users.id, { onDelete: "cascade" }), role: text("role").default("editor").notNull(), permissions: jsonb("permissions").$type<string[]>().default([]).notNull(), lastLoginAt: timestamp("last_login_at", { withTimezone: true }) });

export const sourceDocuments = pgTable("source_documents", { id: uuid("id").defaultRandom().primaryKey(), type: documentType("type").notNull(), title: text("title").notNull(), originalFilename: text("original_filename").notNull(), storageKey: text("storage_key").notNull(), sourceName: text("source_name").notNull(), sourceUrl: text("source_url"), authority: text("authority"), publicationDate: date("publication_date"), fileHash: text("file_hash").notNull(), mimeType: text("mime_type").notNull(), byteSize: integer("byte_size").notNull(), processingStatus: ingestionStatus("processing_status").default("downloaded").notNull(), firstFetchedAt: timestamp("first_fetched_at", { withTimezone: true }).defaultNow().notNull(), lastFetchedAt: timestamp("last_fetched_at", { withTimezone: true }).defaultNow().notNull(), lastVerifiedAt: timestamp("last_verified_at", { withTimezone: true }), ...timestamps }, (t) => [uniqueIndex("source_documents_hash_uq").on(t.fileHash), index("source_documents_type_date_idx").on(t.type, t.publicationDate)]);
export const sourceDocumentVersions = pgTable("source_document_versions", { id: uuid("id").defaultRandom().primaryKey(), sourceDocumentId: uuid("source_document_id").notNull().references(() => sourceDocuments.id, { onDelete: "cascade" }), version: integer("version").notNull(), fileHash: text("file_hash").notNull(), contentHash: text("content_hash"), storageKey: text("storage_key").notNull(), parsedText: text("parsed_text"), parserVersion: text("parser_version"), parsedMetadata: jsonb("parsed_metadata"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex("source_document_versions_uq").on(t.sourceDocumentId, t.version)]);

export const acts = pgTable("acts", { id: uuid("id").defaultRandom().primaryKey(), jurisdiction: text("jurisdiction").default("IN").notNull(), taxDomain: text("tax_domain").notNull(), slug: text("slug").notNull(), shortTitle: text("short_title").notNull(), longTitle: text("long_title"), enactmentDate: date("enactment_date"), status: contentStatus("status").default("draft").notNull(), ...timestamps }, (t) => [uniqueIndex("acts_slug_uq").on(t.slug)]);
export const actVersions = pgTable("act_versions", { id: uuid("id").defaultRandom().primaryKey(), actId: uuid("act_id").notNull().references(() => acts.id, { onDelete: "cascade" }), label: text("label").notNull(), effectiveFrom: date("effective_from"), effectiveTo: date("effective_to"), sourceDocumentVersionId: uuid("source_document_version_id").references(() => sourceDocumentVersions.id), ...timestamps }, (t) => [uniqueIndex("act_versions_label_uq").on(t.actId, t.label)]);
export const actSections = pgTable("act_sections", { id: uuid("id").defaultRandom().primaryKey(), actId: uuid("act_id").notNull().references(() => acts.id, { onDelete: "cascade" }), parentId: uuid("parent_id"), number: text("number").notNull(), slug: text("slug").notNull(), title: text("title").notNull(), sortOrder: integer("sort_order").default(0).notNull(), status: contentStatus("status").default("draft").notNull(), ...timestamps }, (t) => [uniqueIndex("act_sections_slug_uq").on(t.actId, t.slug), index("act_sections_number_idx").on(t.actId, t.number)]);
export const sectionVersions = pgTable("section_versions", { id: uuid("id").defaultRandom().primaryKey(), sectionId: uuid("section_id").notNull().references(() => actSections.id, { onDelete: "cascade" }), actVersionId: uuid("act_version_id").references(() => actVersions.id), officialText: text("official_text").notNull(), aiSummary: text("ai_summary"), aiExplanation: text("ai_explanation"), aiPracticalNotes: jsonb("ai_practical_notes"), effectiveFrom: date("effective_from"), effectiveTo: date("effective_to"), sourceDocumentVersionId: uuid("source_document_version_id").notNull().references(() => sourceDocumentVersions.id), sourceLocator: jsonb("source_locator").$type<{ page?: number; start?: number; end?: number }>().notNull(), lastVerifiedAt: timestamp("last_verified_at", { withTimezone: true }), ...timestamps }, (t) => [index("section_versions_date_idx").on(t.sectionId, t.effectiveFrom)]);

export const rulesets = pgTable("rulesets", { id: uuid("id").defaultRandom().primaryKey(), actId: uuid("act_id").references(() => acts.id), slug: text("slug").notNull().unique(), title: text("title").notNull(), status: contentStatus("status").default("draft").notNull(), ...timestamps });
export const rules = pgTable("rules", { id: uuid("id").defaultRandom().primaryKey(), rulesetId: uuid("ruleset_id").notNull().references(() => rulesets.id, { onDelete: "cascade" }), number: text("number").notNull(), slug: text("slug").notNull(), title: text("title").notNull(), status: contentStatus("status").default("draft").notNull(), ...timestamps }, (t) => [uniqueIndex("rules_slug_uq").on(t.rulesetId, t.slug)]);
export const ruleVersions = pgTable("rule_versions", { id: uuid("id").defaultRandom().primaryKey(), ruleId: uuid("rule_id").notNull().references(() => rules.id, { onDelete: "cascade" }), officialText: text("official_text").notNull(), aiExplanation: text("ai_explanation"), effectiveFrom: date("effective_from"), effectiveTo: date("effective_to"), sourceDocumentVersionId: uuid("source_document_version_id").notNull().references(() => sourceDocumentVersions.id), sourceLocator: jsonb("source_locator").notNull(), ...timestamps });

export const legalDocuments = pgTable("legal_documents", { id: uuid("id").defaultRandom().primaryKey(), type: contentType("type").notNull(), domain: text("domain").notNull(), slug: text("slug").notNull(), documentNumber: text("document_number"), title: text("title").notNull(), subject: text("subject"), authority: text("authority"), issuedOn: date("issued_on"), effectiveFrom: date("effective_from"), officialText: text("official_text"), aiSummary: text("ai_summary"), sourceDocumentVersionId: uuid("source_document_version_id").notNull().references(() => sourceDocumentVersions.id), status: contentStatus("status").default("draft").notNull(), ...timestamps }, (t) => [uniqueIndex("legal_documents_slug_uq").on(t.type, t.slug), index("legal_documents_lookup_idx").on(t.type, t.documentNumber, t.issuedOn)]);

export const cases = pgTable("cases", { id: uuid("id").defaultRandom().primaryKey(), slug: text("slug").notNull().unique(), caseName: text("case_name").notNull(), court: text("court").notNull(), bench: text("bench"), caseNumber: text("case_number"), neutralCitation: text("neutral_citation"), decisionDate: date("decision_date"), appellant: text("appellant"), respondent: text("respondent"), facts: text("facts"), legalIssues: jsonb("legal_issues"), decision: text("decision"), ratioDecidendi: text("ratio_decidendi"), aiSummary: text("ai_summary"), sourceDocumentVersionId: uuid("source_document_version_id").notNull().references(() => sourceDocumentVersions.id), status: contentStatus("status").default("draft").notNull(), ...timestamps });
export const caseJudges = pgTable("case_judges", { caseId: uuid("case_id").notNull().references(() => cases.id, { onDelete: "cascade" }), judgeName: text("judge_name").notNull(), position: integer("position").default(0).notNull() }, (t) => [primaryKey({ columns: [t.caseId, t.judgeName] })]);
export const caseCitations = pgTable("case_citations", { id: uuid("id").defaultRandom().primaryKey(), caseId: uuid("case_id").notNull().references(() => cases.id, { onDelete: "cascade" }), citation: text("citation").notNull(), kind: text("kind").notNull() });

export const contentRelationships = pgTable("content_relationships", { id: uuid("id").defaultRandom().primaryKey(), sourceType: contentType("source_type").notNull(), sourceId: uuid("source_id").notNull(), targetType: contentType("target_type").notNull(), targetId: uuid("target_id").notNull(), relationshipType: text("relationship_type").notNull(), confidence: numeric("confidence", { precision: 5, scale: 4 }), aiSuggested: boolean("ai_suggested").default(false).notNull(), manuallyVerified: boolean("manually_verified").default(false).notNull(), verifiedBy: uuid("verified_by").references(() => users.id), verifiedAt: timestamp("verified_at", { withTimezone: true }), ...timestamps }, (t) => [uniqueIndex("content_relationships_uq").on(t.sourceType, t.sourceId, t.targetType, t.targetId, t.relationshipType), index("relationships_source_idx").on(t.sourceType, t.sourceId, t.manuallyVerified), index("relationships_target_idx").on(t.targetType, t.targetId, t.manuallyVerified)]);

export const ingestionSources = pgTable("ingestion_sources", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), domain: text("domain").notNull(), sourceType: text("source_type").notNull(), baseUrl: text("base_url").notNull(), enabled: boolean("enabled").default(true).notNull(), rateLimitMs: integer("rate_limit_ms").default(1000).notNull(), config: jsonb("config").default({}).notNull(), ...timestamps });
export const ingestionRuns = pgTable("ingestion_runs", { id: uuid("id").defaultRandom().primaryKey(), sourceId: uuid("source_id").notNull().references(() => ingestionSources.id), status: ingestionStatus("status").default("discovered").notNull(), discoveredCount: integer("discovered_count").default(0).notNull(), processedCount: integer("processed_count").default(0).notNull(), failedCount: integer("failed_count").default(0).notNull(), startedAt: timestamp("started_at", { withTimezone: true }), finishedAt: timestamp("finished_at", { withTimezone: true }), error: text("error") });
export const ingestionItems = pgTable("ingestion_items", { id: uuid("id").defaultRandom().primaryKey(), runId: uuid("run_id").notNull().references(() => ingestionRuns.id, { onDelete: "cascade" }), externalId: text("external_id").notNull(), sourceUrl: text("source_url").notNull(), normalizedTitle: text("normalized_title"), documentNumber: text("document_number"), documentDate: date("document_date"), contentHash: text("content_hash"), status: ingestionStatus("status").default("discovered").notNull(), attempts: integer("attempts").default(0).notNull(), payload: jsonb("payload").default({}).notNull(), error: text("error"), ...timestamps }, (t) => [uniqueIndex("ingestion_items_external_uq").on(t.runId, t.externalId), index("ingestion_items_dedupe_idx").on(t.documentNumber, t.documentDate, t.contentHash)]);
export const archiveJudgments = pgTable("archive_judgments", { sourceKey: text("source_key").primaryKey(), cnr: text("cnr"), caseId: text("case_id"), title: text("title").notNull(), courtCode: text("court_code").notNull(), courtName: text("court_name").notNull(), bench: text("bench"), judges: jsonb("judges").$type<string[]>().default([]).notNull(), authorJudge: text("author_judge"), decisionDate: date("decision_date"), registrationDate: date("registration_date"), year: integer("year"), petitioner: text("petitioner"), respondent: text("respondent"), citation: text("citation"), disposalNature: text("disposal_nature"), description: text("description"), pdfPath: text("pdf_path"), pdfExists: boolean("pdf_exists"), availableLanguages: jsonb("available_languages").$type<string[]>().default([]).notNull(), sourceName: text("source_name").default("bharat-courts-archive").notNull(), sourceLicense: text("source_license").default("CC-BY-4.0").notNull(), connectorVersion: text("connector_version").notNull(), rawMetadata: jsonb("raw_metadata").notNull(), status: contentStatus("status").default("needs_review").notNull(), firstFetchedAt: timestamp("first_fetched_at", { withTimezone: true }).defaultNow().notNull(), lastVerifiedAt: timestamp("last_verified_at", { withTimezone: true }).defaultNow().notNull(), ...timestamps }, (t) => [index("archive_judgments_court_year_idx").on(t.courtCode, t.year, t.decisionDate), uniqueIndex("archive_judgments_cnr_uq").on(t.cnr)]);
export const archiveIngestionPartitions = pgTable("archive_ingestion_partitions", { courtCode: text("court_code").notNull(), year: integer("year").notNull(), status: text("status").default("pending").notNull(), importedCount: integer("imported_count").default(0).notNull(), startedAt: timestamp("started_at", { withTimezone: true }), finishedAt: timestamp("finished_at", { withTimezone: true }), error: text("error"), ...timestamps }, (t) => [primaryKey({ columns: [t.courtCode, t.year] })]);
export const aiProcessingJobs = pgTable("ai_processing_jobs", { id: uuid("id").defaultRandom().primaryKey(), jobType: text("job_type").notNull(), entityType: contentType("entity_type"), entityId: uuid("entity_id"), status: text("status").default("queued").notNull(), input: jsonb("input").notNull(), structuredOutput: jsonb("structured_output"), model: text("model"), promptVersion: text("prompt_version"), error: text("error"), ...timestamps });
export const articles = pgTable("articles", { id: uuid("id").defaultRandom().primaryKey(), slug: text("slug").notNull().unique(), title: text("title").notNull(), body: text("body").notNull(), authorId: uuid("author_id").references(() => users.id), status: contentStatus("status").default("draft").notNull(), publishedAt: timestamp("published_at", { withTimezone: true }), ...timestamps });
export const faqs = pgTable("faqs", { id: uuid("id").defaultRandom().primaryKey(), question: text("question").notNull(), answer: text("answer").notNull(), isAiAssisted: boolean("is_ai_assisted").default(false).notNull(), sourceLocator: jsonb("source_locator"), status: contentStatus("status").default("draft").notNull(), ...timestamps });
export const seoMetadata = pgTable("seo_metadata", { id: uuid("id").defaultRandom().primaryKey(), path: text("path").notNull().unique(), title: text("title").notNull(), description: text("description"), canonicalUrl: text("canonical_url"), noIndex: boolean("no_index").default(false).notNull(), openGraph: jsonb("open_graph").default({}).notNull(), structuredData: jsonb("structured_data").default({}).notNull(), ...timestamps });
export const auditLogs = pgTable("audit_logs", { id: uuid("id").defaultRandom().primaryKey(), actorUserId: uuid("actor_user_id").references(() => users.id), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: uuid("entity_id"), before: jsonb("before"), after: jsonb("after"), ipAddress: text("ip_address"), userAgent: text("user_agent"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("audit_logs_entity_idx").on(t.entityType, t.entityId, t.createdAt)]);
