import { useEffect, useState, type FormEvent, type ReactNode } from "react";

type Category = { id: string; name: string; slug: string; status: string; title?: string; active?: boolean };
type AdminItem = { id: string; title?: string; name?: string; status?: string; active?: boolean };
type Content = { categories: Category[]; cases: AdminItem[]; posts: AdminItem[]; partners: AdminItem[]; featured: AdminItem[]; audit: unknown[] };
const empty: Content = { categories: [], cases: [], posts: [], partners: [], featured: [], audit: [] };
function authHeaders(user: string, password: string): Record<string, string> { return user && password ? { Authorization: `Basic ${btoa(`${user}:${password}`)}` } : {}; }
async function request(path: string, body: unknown, user: string, password: string) { const response = await fetch(`/api/admin/${path}`, { method: "POST", headers: { "Content-Type": "application/json", ...authHeaders(user, password) }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? result.error?.code ?? "Request failed"); return result.data; }
const field = "w-full rounded-lg border border-line bg-white px-3 py-2.5 text-sm outline-none focus:border-saffron";

export function AdminPage() {
  const [content, setContent] = useState<Content>(empty); const [tab, setTab] = useState("cases"); const [notice, setNotice] = useState(""); const [user, setUser] = useState(() => sessionStorage.getItem("caselawindia-admin-user") ?? ""); const [password, setPassword] = useState(() => sessionStorage.getItem("caselawindia-admin-password") ?? ""); const [authenticated, setAuthenticated] = useState(false);
  const load = () => fetch("/api/admin/content", { headers: authHeaders(user, password) }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? "Admin access denied."); setContent(result.data ?? empty); setAuthenticated(true); setNotice(""); }).catch((error) => { setAuthenticated(false); setNotice(error instanceof Error ? error.message : "Admin access denied."); });
  useEffect(() => { load(); }, []);
  async function submit(path: string, body: unknown) { try { await request(path, body, user, password); setNotice("Saved successfully."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to save."); } }
  const tabs = [["cases", "Case law"], ["categories", "Categories"], ["posts", "Blog / news"], ["partners", "Partner links"], ["featured", "Featured sidebar"]];
  if (!authenticated) return <main className="mx-auto min-h-[75vh] max-w-md px-5 py-16"><form onSubmit={(event) => { event.preventDefault(); sessionStorage.setItem("caselawindia-admin-user", user); sessionStorage.setItem("caselawindia-admin-password", password); load(); }} className="space-y-4 rounded-xl border border-line bg-white p-7 shadow-sm"><p className="eyebrow">SECURE ACCESS</p><h1 className="font-serif text-3xl">Admin login</h1><input className={field} value={user} onChange={(event) => setUser(event.target.value)} placeholder="User ID" autoComplete="username" required/><input className={field} type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Password" autoComplete="current-password" required/><button className="w-full rounded-lg bg-forest px-5 py-3 text-sm font-bold text-white">Login</button>{notice && <p className="text-sm text-red-700">{notice}</p>}</form></main>;
  const records = tab === "cases" ? content.cases : tab === "categories" ? content.categories : tab === "posts" ? content.posts : tab === "partners" ? content.partners : content.featured;
  return <main className="mx-auto min-h-[75vh] max-w-[1380px] px-5 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">CONTENT MANAGEMENT</p><h1 className="font-serif text-4xl">Admin dashboard</h1></div><button className="text-sm font-bold text-slate-500" onClick={() => { sessionStorage.removeItem("caselawindia-admin-password"); setPassword(""); setAuthenticated(false); }}>Log out</button></div><div className="mt-7 flex flex-wrap gap-2">{tabs.map(([key, label]) => <button key={key} onClick={() => { setTab(key); setNotice(""); }} className={`rounded-lg px-4 py-2 text-sm font-bold ${tab === key ? "bg-forest text-white" : "border border-line bg-white"}`}>{label}</button>)}</div>{notice && <div className="mt-5 rounded-lg border border-line bg-mist p-3 text-sm text-forest">{notice}</div>}<div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_360px]">
    <section>{tab === "cases" && <CaseForm categories={content.categories} onSubmit={(body) => submit("cases", body)}/>} {tab === "categories" && <CategoryForm onSubmit={(body) => submit("categories", body)}/>} {tab === "posts" && <PostForm onSubmit={(body) => submit("posts", body)}/>} {tab === "partners" && <PartnerForm onSubmit={(body) => submit("partners", body)}/>} {tab === "featured" && <FeaturedForm onSubmit={(body) => submit("featured", body)}/>}</section>
    <aside className="h-fit rounded-xl border border-line bg-white p-5"><h2 className="font-serif text-xl">Existing records</h2><div className="mt-4 max-h-[600px] space-y-2 overflow-auto">{records.map((item) => <div key={item.id} className="rounded-lg bg-paper p-3 text-sm"><strong>{item.title ?? item.name ?? item.id}</strong><small className="mt-1 block text-slate-400">{item.status ?? (item.active ? "active" : "inactive")}</small></div>)}</div></aside>
  </div></main>;
}

function CategoryForm({ onSubmit }: { onSubmit: (body: unknown) => void }) { function send(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); onSubmit({ name: data.get("name"), slug: data.get("slug"), description: data.get("description"), status: data.get("status") }); } return <Form title="Create court or tribunal category" onSubmit={send}><input className={field} name="name" placeholder="e.g. National Company Law Appellate Tribunal" required/><input className={field} name="slug" placeholder="nclat" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required/><textarea className={field} name="description" placeholder="Category description" rows={4}/><Status/></Form>; }
function CaseForm({ categories, onSubmit }: { categories: Category[]; onSubmit: (body: unknown) => void }) { function send(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); onSubmit({ title: data.get("title"), slug: data.get("slug"), categoryId: data.get("categoryId"), court: data.get("court"), caseNumber: data.get("caseNumber"), citation: data.get("citation"), decisionDate: data.get("decisionDate"), judges: String(data.get("judges") ?? "").split(",").map((value) => value.trim()).filter(Boolean), parties: data.get("parties"), summary: data.get("summary"), judgmentText: data.get("judgmentText"), sourceUrl: data.get("sourceUrl"), status: data.get("status") }); } return <Form title="Submit case law manually" onSubmit={send}>{categories.length === 0 && <p className="rounded bg-amber-50 p-3 text-sm text-amber-900">Create a category before submitting case law.</p>}<input className={field} name="title" placeholder="Case title" required/><input className={field} name="slug" placeholder="case-title-year" required/><select className={field} name="categoryId" required><option value="">Select category</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><div className="grid gap-3 md:grid-cols-2"><input className={field} name="court" placeholder="Court / tribunal" required/><input className={field} name="decisionDate" type="date" required/><input className={field} name="caseNumber" placeholder="Case number"/><input className={field} name="citation" placeholder="Verified citation"/></div><input className={field} name="judges" placeholder="Judges, separated by commas"/><input className={field} name="parties" placeholder="Parties"/><textarea className={field} name="summary" placeholder="Editorial summary" rows={5}/><textarea className={field} name="judgmentText" placeholder="Complete judgment text" rows={14} required/><input className={field} name="sourceUrl" type="url" placeholder="Official source URL (required to publish)"/><Status/></Form>; }
function PostForm({ onSubmit }: { onSubmit: (body: unknown) => void }) { function send(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); onSubmit({ title: data.get("title"), slug: data.get("slug"), excerpt: data.get("excerpt"), body: data.get("body"), author: data.get("author"), status: data.get("status"), publishedAt: null }); } return <Form title="Create blog or news post" onSubmit={send}><input className={field} name="title" placeholder="Post title" required/><input className={field} name="slug" placeholder="post-url-slug" required/><input className={field} name="author" placeholder="Author" required/><textarea className={field} name="excerpt" placeholder="Short excerpt" rows={3} required/><textarea className={field} name="body" placeholder="Article body" rows={14} required/><Status/></Form>; }
function PartnerForm({ onSubmit }: { onSubmit: (body: unknown) => void }) { function send(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); onSubmit({ name: data.get("name"), label: data.get("label"), url: data.get("url"), placement: data.get("placement"), active: data.get("active") === "on", disclosure: data.get("disclosure") }); } return <Form title="Configure partner placement" onSubmit={send}><input className={field} name="name" placeholder="Partner name" required/><input className={field} name="label" placeholder="Natural call-to-action label" required/><input className={field} name="url" type="url" placeholder="Add destination URL later"/><select className={field} name="placement"><option value="sidebar">Sidebar</option><option value="inline">Inline</option><option value="both">Both</option></select><input className={field} name="disclosure" defaultValue="Partner service" placeholder="Disclosure label" required/><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="active"/> Activate link (requires URL)</label></Form>; }
function FeaturedForm({ onSubmit }: { onSubmit: (body: unknown) => void }) { function send(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); onSubmit({ title: data.get("title"), description: data.get("description"), url: data.get("url"), label: data.get("label"), active: data.get("active") === "on" }); } return <Form title="Add featured sidebar item" onSubmit={send}><input className={field} name="title" placeholder="Featured title" required/><textarea className={field} name="description" placeholder="Short description" rows={4} required/><input className={field} name="url" placeholder="Internal path (/blog/...) or full URL" required/><input className={field} name="label" placeholder="Read more" required/><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="active" defaultChecked/> Show in sidebar</label></Form>; }
function Status() { return <select className={field} name="status" defaultValue="draft"><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select>; }
function Form({ title, onSubmit, children }: { title: string; onSubmit: (event: FormEvent<HTMLFormElement>) => void; children: ReactNode }) { return <form onSubmit={onSubmit} className="space-y-4 rounded-xl border border-line bg-white p-6 shadow-sm"><h2 className="font-serif text-2xl">{title}</h2>{children}<button className="rounded-lg bg-forest px-5 py-3 text-sm font-bold text-white">Save record</button></form>; }
